name: pestast CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Clippy
      run: cargo clippy --workspace --verbose
    - name: Check
      run: cargo check --workspace --verbose
    - name: Docs
      run: cargo doc --workspace --verbose
